### ISSUE TITLE
PySide6: Launch Qt Designer with plugin support

### ISSUE THREAD

**Issue by maflAT** [seanwu1105/vscode-qt-for-python#285] opened 2023-03-04 08:16 UTC
Hi,
I'm using PySide6 and have Qt Designer configured to load my custom widgets as plugins.
I'm following the process described here: [custom-widgets-in-qt-designer](https://doc.qt.io/qtforpython/tutorials/basictutorial/uifiles.html#custom-widgets-in-qt-designer)

When I launch Qt Designer via this extensions' `Edit Qt UI File (designer)` command, those widgets are not loaded.

According to the guide linked above, there are some caveats to get plugin support working.
One of them is, that you must launch Qt Designer via `.../Scripts/pyside6-designer.exe`,  
not `.../Lib/site-packages/PySide6/designer.exe`!
I suspect that this might be the issue here.

**Expected behaviour:**
(Qt Designer launched via `.../Scripts/pyside6-designer.exe`)
![.../Scripts/pyside6-designer.exe](https://user-images.githubusercontent.com/13979550/222883513-96372c5b-2813-471d-b9d4-f08b4081c095.png ".../Scripts/pyside6-designer.exe")

**Actual Behaviour:**
(Qt Designer launched via `.../Lib/site-packages/PySide6/designer.exe`)
![.../Lib/site-packages/PySide6/designer.exe](https://user-images.githubusercontent.com/13979550/222884846-719f64be-53cd-4ffd-89c3-f6a9d83b84e5.png ".../lib/site-packages/designer.exe")

**Comment by seanwu1105** [comment] 2023-03-04 21:11
Hi @maflAT,

Thanks for the report. Currently, the extension calls [`PySide6.scripts.pyside_tool.designer()`](https://github.com/seanwu1105/vscode-qt-for-python/blob/master/python/scripts/designer.py), which is the same function used in the `pyside6-designer` script, for the _Edit Qt UI File (designer)_ command. Thus, it is unlikely they behave differently though I have not verified it manually.

Could you do me a favor to clarify the problem? Set the `qtForPython.designer.path` to `.../Scripts/pyside6-designer.exe` directly in the extension configuration, and see if the plugins is loaded. If the plugins is still not loaded, it is likely the cause of the problem is somewhere else.

**Comment by maflAT** [comment] 2023-03-05 05:49
You're right. 
I set the path manually and tried again. Plugins are still not loaded.

I also tried another thing:
For my trails in the initial post, I had a virtual environment active.
Launching the `pyside6-designer.exe` from the terminal with venv deactivated will also fail to load plugins.

**Comment by seanwu1105** [comment] 2023-03-05 15:49
@maflAT Could you try to activate the virtual environment by selecting the correct Python interpreter and then call the command? The extension calls [PySide6.scripts.pyside_tool.designer()](https://github.com/seanwu1105/vscode-qt-for-python/blob/master/python/scripts/designer.py) with your selected Python interpreter. Thus, the extension command should work correctly with plugins loaded if it works with virtual environment active. Let me know if it works or not.

**Comment by maflAT** [comment] 2023-03-07 05:47
@seanwu1105 Sorry for the delay.
I tried the following:

1. launching `pyside6-designer` from the terminal without venv active: no plugins
2. running `Edit Qt UI File (designer)` without venv active: no plugins
3. launching `pyside6-designer` from the terminal with active venv: plugins loaded
4. running `Edit Qt UI File (designer)` with active venv: no plugins

**Comment by svenwanzenried** [comment] 2023-03-07 10:22
I stumbled upon the exact same issue today. I tried all the above. Just to clarify: I did not just activate the Python environment inside the terminal window but I activated it using the vscode command "Python: Select Interpreter". When I have a *.py file open in the current window, I can see the active venv in the status bar:
![2023-03-07 11_19_29-](https://user-images.githubusercontent.com/61381861/223394090-25dd0a7f-16e4-4c65-aa4e-6c63d4be2310.png)

Could it be, that somehow the python virtual environment does not get activated, when the target file of a command is not a *.py file but has the ending *.ui?

**Comment by svenwanzenried** [comment] 2023-03-07 12:01
I start a new comment for this one:
I inserted following snippet to `.venv\Lib\site-packages\PySide6\scripts\pyside_tool.py` Line 69 in function qt_tool_wrapper()
```python
print('\n')
print('Interpreter: ' + str(sys.executable))
print('CMD: ' + str(cmd))
print('PYSIDE_DESIGNER_PLUGINS: ' + str(os.environ).replace(", '", ",\n'"))
print('\n')
raise Exception()
```

Afterwards, I executed:
1) vscode command "Edit Qt UI file (designer)" with the file `C:\Repos\PySideTest\untitled\form2.ui`
2) in terminal with active virtual environment `pyside6-designer C:\Repos\PySideTest\untitled\form2.ui`

Both commands expectantly threw an exception (because of the above snippet. I copied both tracelogs into files and made a diff comparision (after some clean-up formatting in both files).
[cmd_in_vscode.txt](https://github.com/seanwu1105/vscode-qt-for-python/files/10909032/cmd_in_vscode.txt)
[cmd_in_terminal.txt](https://github.com/seanwu1105/vscode-qt-for-python/files/10909036/cmd_in_terminal.txt)
If you make the comparison you will see, there are quite some differences in the environment variables. Even some that have to do with the python virtual environment. But i am not experienced enough to interpret these results and what they have to to with the different behavior between these commands.

When I deleted the above snippet, the behavior was as before:
1) Custom plugins not loaded
2) Custom plugins loaded

**Comment by seanwu1105** [comment] 2023-03-07 20:18
For Windows users, the root cause of the problem is from the upstream. If you first activated the virtual environment by the script (e.g. `activate.ps1`) and then invoked `pyside6-designer`, the plugins should be loaded correctly. However, if you try to call the `pyside6-designer` living in the virtual environment __directly__ (e.g. `.\.venv\Scripts\pyside6-designer.exe`) without running the activate script, which is what the extension does, no plugin will be loaded.

Interestingly, if you set the `VIRTUAL_ENV` variable before calling the `pyside6-designer` directly, it loads correctly.

```powershell
$Env:VIRTUAL_ENV = 'C:\Absolute\Path\To\Your\VENV\.venv'
.\.venv\Scripts\pyside6-designer.exe
```

It seems the Qt Designer depends on `VIRTUAL_ENV` to work but it should not due to the warning mentioned in [the official docs](https://docs.python.org/3/library/venv.html#how-venvs-work). I have open an issue [here](https://bugreports.qt.io/browse/PYSIDE-2251) to see what would be the best option to fix this problem. If they decide to keep the currently behavior, I might need to write a workaround to set the `VIRTUAL_ENV` manually from this extension, which is definitely not ideal 😞.

---

For Linux users, if you find the plugins do not loaded correctly with the following error message, it could be caused by [this issue](https://bugreports.qt.io/browse/PYSIDE-2250) though I haven't verified it yet.

**Comment by seanwu1105** [comment] 2023-03-08 22:55
It seems we have to set the `VIRTUAL_ENV` manually by this extension as a workaround since the issue I opened has been marked out-of-scope.

**Comment by svenwanzenried** [comment] 2023-03-09 04:11
I added a comment in your Qt Issue. I think it would be actually possible for them to resolve the issue. At least when the designer is called via their "pyside_tool.py" which is what your extension does, correct?
If they would check there for sys.prefix they could make the use of VIRTUAL_ENV mostly transparent to the user.

**Comment by seanwu1105** [comment] 2023-03-09 12:53
@svenwanzenried Thanks for the comments on the thread. You are correct, and hopefully they can have a simple fix to free the dependency on `VIRTUAL_ENV`.

**Comment by seanwu1105** [comment] 2023-09-10 21:39
Hi @maflAT and @svenwanzenried, sorry it's a bit late. Is the problem resolved by [the fixed issue](https://bugreports.qt.io/browse/PYSIDE-2251)?

**Comment by maflAT** [comment] 2023-09-11 04:53
@seanwu1105 Yes this is fixed. Tested with PySide 6.5.2.

**Comment by seanwu1105** [comment] 2023-09-11 12:41
Awesome! Thanks for letting me know.

**Closed by seanwu1105** 2023-09-11 12:41 UTC
Labels: bug
