### ISSUE TITLE
Cannot find any installed Qt for Python module to use the designer tool

### ISSUE THREAD

**Issue by ShayBox** [seanwu1105/vscode-qt-for-python#113] opened 2021-05-04 18:43 UTC
I have PySide6 installed, and clicking "Install PySide6" says I have it installed and meets requirements
I can't compile or edit ui files, `uic`, `pyside6-uic`, `pyside6-designer` commands are available and in path

**Comment by ShayBox** [comment] 2021-05-04 18:47
Manually entering the paths for them in the settings fixes the problem, it's just not able to auto-detect them, and it's compiling the ui files into .qt_for_python/uic/{file}, not the same directory as the ui file, it's also compiling every ui file in every workspace folder into my single active workspace folder which is not what I want
![image](https://user-images.githubusercontent.com/9505196/117053966-96a8cd80-ace7-11eb-9315-145c6db958a0.png)

**Comment by seanwu1105** [comment] 2021-05-05 03:58
@ShayBox

The extension will try to use the currently active Python path via `python.pythonPath` in your Visual Studio Code configuration to execute the Qt tools, such as [`uic.py`](https://github.com/seanwu1105/vscode-qt-for-python/blob/master/python/scripts/uic.py). If the tool cannot be found by [searching `sys.modules` and `importlib.utils.find_spec`](https://github.com/seanwu1105/vscode-qt-for-python/blob/1ec6ddb0919b1752ce1628e58a252d6442acb0a6/python/scripts/common.py#L7), the extension will assume the packages providing the tool is not installed with your active Python interpreter. Thus, could you make sure you can import the tool __programmatically__ in currently active Python runtime for your project? For example,

```py
from PySide6.scripts.pyside_tool import uic as main
```

Regarding the "auto-compilation" behavior, it currently only supports single workspace. A PR to enhance this feature is always welcome! You can always opt out the behavior by settings the configuration `qtForPython.<TOOL_NAME>.liveExecution` to `false`.

**Comment by ShayBox** [comment] 2021-05-05 04:01
Using programmatic imports is probably a bad idea, using seperated envs for everything is very common and recommended on both pyside and pyqt officially

**Comment by seanwu1105** [comment] 2021-05-05 05:40
@ShayBox Actually, the official implementation of PySide and PyQt tools, such as [`pyside6-uic`](https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/pyside-tools/pyside_tool.py?h=6.0.4) and `pylupdate5` is programmatic imports with Python scripts. By doing so, you can use seperated environments depending on your active Python interpreter. Also, the users do not have to care the internal implementation about how to invoke the tool.  After all, you can still statically set the tool path manually via the extension configuration.

I find your RidenGUI project in your GitHub profile. I will try to reproduce the auto-detection problem you mentioned in your first comment if I have time.

**Comment by seanwu1105** [comment] 2021-06-02 15:53
Close as I could not reproduce the issue. Please provide a minimal sample project with steps to reproduce the issue.

**Comment by ugur1yildiz** [comment] 2021-12-10 16:39
While using venv type virtual envioriment the extension cannot find the PySide6 executables giving the error with the issue title. Altough in settings.json paths are set as "${workspaceFolder}\\Scripts\\pyside6-xxx.exe", and all the executable are there, It cannot find the files. It may be ${workspaceFolder} doesn't work.

**Comment by seanwu1105** [comment] 2021-12-10 16:46
Currently, the path of executables will not be resolved by the environment variables and settings. This feature could be added to the next release. A PR is always welcome.

**Comment by ugur1yildiz** [comment] 2021-12-10 21:34
I couldn't make it work even without venv and with entering absolute paths for "`qtForPython.path.xxx`" and for "`python.defaultInterpreterPath`". I used for terminal both command prompt and powerShell. It gives the same error.

**Comment by seanwu1105** [comment] 2021-12-10 22:45
@ugur1yildiz You should set the path manually with `qtForPython.xxx.path` instead of `qtForPython.path.xxx`. If there is still a problem, please let me know the message showing up and any other details for me to reproduce the problem. Thank you!

**Comment by ugur1yildiz** [comment] 2021-12-10 23:14
> @ugur1yildiz You should set the path manually with `qtForPython.xxx.path` instead of `qtForPython.path.xxx`. If there is still a problem, please let me know the message showing up and any other details for me to reproduce the problem. Thank you!

It worked. Thanks. FYI I didn't write the settings name in json file. They were automatically written by some means after clicking "Set Tool Path" in the error box.

**Comment by seanwu1105** [comment] 2021-12-11 00:25
@ugur1yildiz It is possible that the version of the extension you were using is not up-to-date as I cannot reproduce the wrong setting generation by clicking "Set Tool Path" with the latest version. Anyway, if you find any issue, feel free to open another issue.

**Closed by seanwu1105** 2021-12-11 00:25 UTC

**Comment by xiaoxstz** [comment] 2022-06-19 09:42
I also came across this issue.

After I clicked the button `Set Tool Path`, and then selected the designer.exe, the path is set as the value of "qtForPython.designer.path" in the file `.vscode\settings.json`

![image](https://user-images.githubusercontent.com/81862747/174474138-88e599c7-0ab6-4b6d-8331-9329686a59f1.png)

# My Environment
* OS: Windows 10
* Python version (base): 3.8.8
* Python version (PySide6): 3.9.9. This is the current python environment I used.

# My discovery
When the python environment of the terminal is `PySide`,  the following command runs correctly 
```bash
"C:\Users\tanzi\.conda\envs\PySide6\Scripts\pyside6-designer.exe" ".\Weather.ui"
```

However, when the python environment of the terminal is `base`,  the command above throw errors below
> Error: Fatal Python error: init_import_size: Failed to import the site module
>
> Python runtime state: initialized
>
> Traceback (most recent call last):
>
> File "C:\Users\tanzi\.conda\envs\PySide6\lib\site.py", line 73, in <module>
>
>   import os
>
>  File "C:\Users\tanzi\.conda\envs\PySide6\lib\os.py", line 29, in <module>
>
>   from _collections_abc import _check_methods
>
> File "C:\Users\tanzi\.conda\envs\PySide6\lib\_collections_abc.py", line 12, in <module>
>
>    GenericAlias = type(list[int])
>
> TypeError: 'type' object is not subscriptable

The error is caused by "GenericAlias = type(list[int])" that it's right in Python3.9.9 and wrong in Python 3.8.8

# The solution
According to the discovery, I solved the issue (but not in an ideal way).

Add the setting below to `.vscode\settings.json` (setting of the current workspace)  or `Setting.json` (setting of VS Code)

```json
{
    // First-type set: it will throw "Cannot find any installed Qt for Python module to use the designer tool"
    // "qtForPython.designer.path": "c:\\Users\\tanzi\\.conda\\envs\\PySide6\\Scripts\\pyside6-designer.exe",
    // Second-type set: correct. But the designer is not what I want
    "qtForPython.designer.path": "C:\\ProgramData\\Anaconda3\\Scripts\\pyside6-designer.exe",
}
```
